/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package url.redes2crud;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author aleja
 */
public class EliminarPanel extends javax.swing.JPanel {

    /**
     * Creates new form EliminarPanel
     */
        Conexion cc = new Conexion();
    Connection cn = cc.getConnection();
    public EliminarPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtIngresar = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(740, 470));
        setMinimumSize(new java.awt.Dimension(740, 470));
        setPreferredSize(new java.awt.Dimension(740, 470));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setText(".");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 350, -1, -1));

        txtName.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtName.setForeground(new java.awt.Color(204, 204, 204));
        txtName.setBorder(null);
        txtName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtNameMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txtNameMouseReleased(evt);
            }
        });
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 240, 20));

        jLabel7.setText("________________________________________________");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 300, -1));

        jLabel1.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel1.setText("Ingrese nombre de producto a eliminar");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, -1, -1));

        jLabel10.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(234, 199, 199));
        jLabel10.setText("PRODUCTO");
        jLabel10.setFocusable(false);
        jLabel10.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, 150, 40));

        jLabel11.setBackground(new java.awt.Color(234, 199, 199));
        jLabel11.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("ELIMINAR");
        jLabel11.setFocusable(false);
        jLabel11.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel11.setOpaque(true);
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, -1, 40));

        txtIngresar.setBackground(new java.awt.Color(234, 224, 218));
        txtIngresar.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        txtIngresar.setForeground(new java.awt.Color(153, 153, 153));
        txtIngresar.setText("  ELIMINAR");
        txtIngresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtIngresar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        txtIngresar.setOpaque(true);
        txtIngresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtIngresarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtIngresarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtIngresarMouseExited(evt);
            }
        });
        add(txtIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, 100, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNameMousePressed
        // TODO add your handling code here:
        if (txtName.getText().equals("Ingrese nombre del producto...")) {
            txtName.setText("");
            txtName.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtNameMousePressed

    private void txtNameMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNameMouseReleased

    }//GEN-LAST:event_txtNameMouseReleased

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtIngresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtIngresarMouseClicked
        // TODO add your handling code here:
         try {
            // TODO add your handling code here:
            PreparedStatement pst = cn.prepareStatement("CALL eliminar_producto_por_nombre (?)");
            pst.setString(1, txtName.getText());
            pst.executeUpdate();
            //JOptionPane.showMessageDialog(rootPane, "Ingresado");
            jLabel5.setText("producto eliminado");
            txtName.setText("");

        } catch (SQLException ex) {
            Logger.getLogger(ModificarPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtIngresarMouseClicked

    private void txtIngresarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtIngresarMouseEntered
        // TODO add your handling code here:
        txtIngresar.setBackground(new Color(234, 199, 199));
    }//GEN-LAST:event_txtIngresarMouseEntered

    private void txtIngresarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtIngresarMouseExited
        // TODO add your handling code here:
        txtIngresar.setBackground(new Color(234, 224, 218));
    }//GEN-LAST:event_txtIngresarMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel txtIngresar;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
