/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package url.redes2crud;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author aleja
 */
public class IngresarPanel extends javax.swing.JPanel {

    Conexion cc = new Conexion();
    Connection cn = cc.getConnection();
    /**
     * Creates new form IngresarPanel
     */
    public IngresarPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtprecio = new javax.swing.JTextField();
        txtdes = new javax.swing.JTextField();
        txttotal = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtIngresar = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(740, 470));
        setPreferredSize(new java.awt.Dimension(740, 470));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel1.setText("Nombre");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, -1, -1));

        jLabel2.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel2.setText("Precio");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, -1, -1));

        jLabel3.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel3.setText("Descripción");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, -1, -1));

        txtname.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtname.setForeground(new java.awt.Color(204, 204, 204));
        txtname.setText("Ingrese nombre de producto...");
        txtname.setBorder(null);
        txtname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtnameMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txtnameMouseReleased(evt);
            }
        });
        txtname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnameActionPerformed(evt);
            }
        });
        add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 230, 20));

        jLabel4.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel4.setText("Cantidad");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, -1, -1));

        txtprecio.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtprecio.setForeground(new java.awt.Color(204, 204, 204));
        txtprecio.setText("Ingrese precio de producto...");
        txtprecio.setBorder(null);
        txtprecio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtprecioMousePressed(evt);
            }
        });
        add(txtprecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 230, 20));

        txtdes.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtdes.setForeground(new java.awt.Color(204, 204, 204));
        txtdes.setText("Ingrese descripcion de producto...");
        txtdes.setBorder(null);
        txtdes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtdesMousePressed(evt);
            }
        });
        add(txtdes, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 230, 20));

        txttotal.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txttotal.setForeground(new java.awt.Color(204, 204, 204));
        txttotal.setText("Ingrese cantidad de producto...");
        txttotal.setBorder(null);
        txttotal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txttotalMousePressed(evt);
            }
        });
        txttotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttotalActionPerformed(evt);
            }
        });
        add(txttotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, 230, 20));

        jLabel6.setText("________________________________________________");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, -1, 30));

        jLabel7.setText("________________________________________________");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, -1, -1));

        jLabel8.setText("________________________________________________");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, -1, 20));

        jLabel9.setText("________________________________________________");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, -1, 20));

        txtIngresar.setBackground(new java.awt.Color(234, 224, 218));
        txtIngresar.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        txtIngresar.setForeground(new java.awt.Color(153, 153, 153));
        txtIngresar.setText("  INGRESAR");
        txtIngresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtIngresar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        txtIngresar.setOpaque(true);
        txtIngresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtIngresarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtIngresarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtIngresarMouseExited(evt);
            }
        });
        add(txtIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 360, 100, 50));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(160, 195, 210));
        jLabel5.setText(".");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 420, 240, -1));

        jLabel10.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(234, 199, 199));
        jLabel10.setText("PRODUCTO");
        jLabel10.setFocusable(false);
        jLabel10.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 150, 40));

        jLabel11.setBackground(new java.awt.Color(234, 199, 199));
        jLabel11.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText(" NUEVO ");
        jLabel11.setFocusable(false);
        jLabel11.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel11.setOpaque(true);
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, -1, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void txtprecioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtprecioMousePressed
        // TODO add your handling code here:
        if (txtprecio.getText().equals("Ingrese precio de producto...")) {
            txtprecio.setText("");
            txtprecio.setForeground(Color.black);
        }
        if (String.valueOf(txtname.getText()).isEmpty()) {
            txtname.setText("Ingrese nombre de producto...");
            txtname.setForeground(Color.gray);
        }
        if (String.valueOf(txtdes.getText()).isEmpty()) {
            txtdes.setText("Ingrese descripcion de producto...");
            txtdes.setForeground(Color.gray);
        }
        if (String.valueOf(txttotal.getText()).isEmpty()) {
            txttotal.setText("Ingrese cantidad de producto...");
            txttotal.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtprecioMousePressed

    private void txtdesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtdesMousePressed
        // TODO add your handling code here:
        if (txtdes.getText().equals("Ingrese descripcion de producto...")) {
            txtdes.setText("");
            txtdes.setForeground(Color.black);
        }
        if (String.valueOf(txtprecio.getText()).isEmpty()) {
            txtprecio.setText("Ingrese precio de producto...");
            txtprecio.setForeground(Color.gray);
        }
        if (String.valueOf(txtname.getText()).isEmpty()) {
            txtname.setText("Ingrese nombre de producto...");
            txtname.setForeground(Color.gray);
        }
        if (String.valueOf(txttotal.getText()).isEmpty()) {
            txttotal.setText("Ingrese cantidad de producto...");
            txttotal.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtdesMousePressed

    private void txttotalMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txttotalMousePressed
        // TODO add your handling code here:
        if (txttotal.getText().equals("Ingrese cantidad de producto...")) {
            txttotal.setText("");
            txttotal.setForeground(Color.black);
        }
        if (String.valueOf(txtprecio.getText()).isEmpty()) {
            txtprecio.setText("Ingrese precio de producto...");
            txtprecio.setForeground(Color.gray);
        }
        if (String.valueOf(txtname.getText()).isEmpty()) {
            txtname.setText("Ingrese nombre de producto...");
            txtname.setForeground(Color.gray);
        }

        if (String.valueOf(txtdes.getText()).isEmpty()) {
            txtdes.setText("Ingrese descripcion de producto...");
            txtdes.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txttotalMousePressed

    private void txttotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttotalActionPerformed

    private void txtIngresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtIngresarMouseClicked
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            PreparedStatement pst = cn.prepareStatement("CALL IngresarProducto (?,?,?,?)");
            pst.setString(1,(txtname.getText()));
            pst.setDouble(2, Integer.parseInt(txtprecio.getText()));
            pst.setString(3, txtdes.getText());
            pst.setInt(4, Integer.parseInt(txttotal.getText()));
            pst.executeUpdate();
            //JOptionPane.showMessageDialog(rootPane, "Ingresado");
            jLabel5.setText("Producto ingresada");
            txtname.setText("");
            txtprecio.setText("");
            txtdes.setText("");
            txttotal.setText("");

        } catch (SQLException ex) {
            Logger.getLogger(IngresarPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtIngresarMouseClicked

    private void txtIngresarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtIngresarMouseEntered
        // TODO add your handling code here:
        txtIngresar.setBackground(new Color(234, 199, 199));
    }//GEN-LAST:event_txtIngresarMouseEntered

    private void txtIngresarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtIngresarMouseExited
        // TODO add your handling code here:
        txtIngresar.setBackground(new Color(234, 224, 218));
    }//GEN-LAST:event_txtIngresarMouseExited

    private void txtnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnameActionPerformed

    private void txtnameMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtnameMouseReleased

    }//GEN-LAST:event_txtnameMouseReleased

    private void txtnameMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtnameMousePressed
        // TODO add your handling code here:
        if (txtname.getText().equals("Ingrese nombre de producto...")) {
            txtname.setText("");
            txtname.setForeground(Color.black);
        }
        if (String.valueOf(txtprecio.getText()).isEmpty()) {
            txtprecio.setText("Ingrese precio de producto...");
            txtprecio.setForeground(Color.gray);
        }
        if (String.valueOf(txtdes.getText()).isEmpty()) {
            txtdes.setText("Ingrese descripcion de producto...");
            txtdes.setForeground(Color.gray);
        }
        if (String.valueOf(txttotal.getText()).isEmpty()) {
            txttotal.setText("Ingrese cantidad de producto...");
            txttotal.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtnameMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel txtIngresar;
    private javax.swing.JTextField txtdes;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtprecio;
    private javax.swing.JTextField txttotal;
    // End of variables declaration//GEN-END:variables
}
